artifact_location: file:C:/Users/Admins/MLOpsProject/mlruns_dvc/611289215057951396
creation_time: 1776315491341
experiment_id: '611289215057951396'
last_update_time: 1776315491341
lifecycle_stage: active
name: Telco_Churn_Model
trace_location: null
workspace: default
