apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: churn-api-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: churn-api
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s
